Footer
Nezerwa/Ojemba-VLM-Project pull request #15
Opened 2023-08-19 12:48 UTC by peninah98

# Description
Fragen section

## How Has This Been Tested and How are your changes run?
To review this project, first see the output screenshot below
clone the project to review it in local machine here is the [link](https://github.com/Nezerwa/Ojemba-VLM-Project)
Run `npm run build` to run the project in locally

## Screenshots of output:
![image](https://github.com/Nezerwa/Ojemba-VLM-Project/assets/78850411/4b7d22f3-7d8d-434e-9ffa-d6122a54db99)

2023-08-20 19:13 UTC, ell-sie reviewed
The footer looks Great !

2023-08-21 10:50 UTC, alainmigabo requested changes

2023-08-21 10:50 UTC, alainmigabo commented on images/DSC_7863.jpg
Please Remove this image

2023-08-21 10:59 UTC, alainmigabo commented
Please resolve the conflicts then

2023-08-21 11:05 UTC, alainmigabo approved these changes

2023-08-21 11:08 UTC, ell-sie approved these changes
Well done !

2023-08-21 11:08 UTC, merged