fix: filled the alt attributes and deleted the empty classes
Nezerwa/Ojemba-VLM-Project pull request #61
Opened 2023-08-31 16:15 UTC by ell-sie

##Desrcription
- [x] alt attributes should not be empty
- [x] Button classes should not be empty , if are not needed remove them

2023-08-31 17:44 UTC, peninah98 requested changes
You van work on naming of images aly

2023-09-01 08:14 UTC, Nezerwa approved these changes
well done, it's time to merge

2023-09-01 08:17 UTC, alainmigabo approved these changes

2023-09-01 08:21 UTC, peninah98 approved these changes

2023-09-01 08:21 UTC, merged